### ISSUE TITLE
AC 后报错

### ISSUE THREAD

**Issue by Kewth** [syzoj/syzoj-tools#3]
原本没有问题，但是在克隆源码安装之后，评测 AC会得到这样的结果（报错没有 wcmp 这样的文件）：
```
VERBOSE:compiled-language:Compiling source code source/CSYZ14/treasure.cpp
VERBOSE:compiled-language:Compilation success
VERBOSE:problem:Judging subtask 0
VERBOSE:problem-traditional:Running testcase 1
Traceback (most recent call last):
  File "/home/kewth/.local/bin/syzoj", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/kewth/Kewth_/syzoj-tools/bin/syzoj", line 4, in <module>
    syzoj_tools.main()
  File "/home/kewth/Kewth_/syzoj-tools/syzoj_tools/__init__.py", line 60, in main
    args.func(args)
  File "/home/kewth/Kewth_/syzoj-tools/syzoj_tools/__init__.py", line 83, in cmd_judge
    result = problem.judge(prog, lazy=args.lazy)
  File "/home/kewth/Kewth_/syzoj-tools/syzoj_tools/problem.py", line 199, in judge
    case_result[j] = session.do_judge(case)
  File "/home/kewth/Kewth_/syzoj-tools/syzoj_tools/types/traditional.py", line 89, in do_judge
    checker_result = self.parent.checker.check(case, run_result.outfile)
  File "/home/kewth/Kewth_/syzoj-tools/syzoj_tools/checkers/builtin.py", line 19, in check
    return run_testlib_checker(checker_file, case.input_data, outfile, case.answer_data)
  File "/home/kewth/Kewth_/syzoj-tools/syzoj_tools/checkers/__init__.py", line 45, in run_testlib_checker
    subprocess.run([checker, input, output, answer, result_file.name], check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
  File "/usr/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/kewth/Kewth_/syzoj-tools/syzoj_tools/checkers/wcmp': '/home/kewth/Kewth_/syzoj-tools/syzoj_tools/checkers/wcmp'
```

不知道是否是操作不当？

**Comment by vincent-163** [comment]
这里是文档里没写清楚，克隆源码安装得到的 syzoj-tools 其实不太完整，因为 syzoj_tools/checkers 里面有一些内置的 checker 需要编译后才能使用，并且编译会花费不少时间。要获得最新的版本的话最好还是用文档里的下载链接。

**Comment by vincent-163** [comment]
现在把自动编译 checker 的功能加回来了：https://github.com/syzoj/syzoj-tools/commit/62ec4b1fbeb3ad01f784405be2ce1663da2eb9e2
问题应该暂时解决了。但还是要注意 `pip3 install -e .` 命令安装时会省略掉编译步骤，需要手动编译。`pip3 install .` 才会执行编译，但这样做的话无法把修改直接反映到程序上。
